package prusalink

import (
	"io"
	"reflect"
	"strings"
	"testing"

	"github.com/ccmpbll/printspy/printmeta"
)

// head (thumbnail) + 300MB-equivalent body streamed lazily + footer config.
func bigGcode() io.Reader {
	head := "; generated by PrusaSlicer\n; thumbnail begin 16x16 8\n; iVBORw0KGgo=\n; thumbnail end\n"
	body := io.LimitReader(repeat("G1 X10.123 Y20.456 E0.01234 F1800\n"), 300<<20)
	foot := "; total filament used [g] = 12.34\n; layer_height = 0.2\n; filament_type = PLA\n"
	return io.MultiReader(strings.NewReader(head), body, strings.NewReader(foot))
}

type repeat string

func (r repeat) Read(p []byte) (int, error) {
	n := 0
	for n+len(r) <= len(p) {
		n += copy(p[n:], r)
	}
	if n == 0 {
		n = copy(p, r)
	}
	return n, nil
}

func TestKeepGcodeCommentsBoundsMemoryAndPreservesMetadata(t *testing.T) {
	kept, err := keepGcodeComments(bigGcode())
	if err != nil {
		t.Fatal(err)
	}
	if len(kept) > 1<<10 {
		t.Fatalf("kept %d bytes from a body with no comments", len(kept))
	}
	info, err := printmeta.Parse("big.gcode", kept)
	if err != nil {
		t.Fatal(err)
	}
	if info.LayerHeightMM != 0.2 || info.Material != "PLA" {
		t.Errorf("footer metadata lost: %+v", info)
	}
	if len(info.Thumbnail) == 0 {
		t.Error("thumbnail lost")
	}
}

func TestKeepGcodeCommentsCapsCommentFlood(t *testing.T) {
	flood := io.LimitReader(repeat("; layer comment padding padding padding\n"), 64<<20)
	kept, err := keepGcodeComments(flood)
	if err != nil || len(kept) > maxKeptGcodeComments {
		t.Fatalf("len=%d err=%v", len(kept), err)
	}
}

func TestFilteredParseEqualsFullParse(t *testing.T) {
	full, _ := io.ReadAll(io.MultiReader(strings.NewReader("; thumbnail begin 16x16 8\n; iVBORw0KGgo=\n; thumbnail end\n;LAYER_CHANGE\n"),
		io.LimitReader(repeat("G1 X1 Y2 E.1\n;TYPE:Perimeter\n"), 1<<20), strings.NewReader("; total filament used [g] = 12.34\n; layer_height = 0.2\n")))
	kept, err := keepGcodeComments(strings.NewReader(string(full)))
	if err != nil {
		t.Fatal(err)
	}
	a, _ := printmeta.Parse("x.gcode", full)
	b, _ := printmeta.Parse("x.gcode", kept)
	if !reflect.DeepEqual(a, b) {
		t.Errorf("filtered parse differs:\n%+v\n%+v", a, b)
	}
}
